### ISSUE TITLE
Patch executed multiple times

### ISSUE THREAD

**Issue by grad-michal** [DW2MC/DW2ModLoader#8]
Hi,

I created simple patch:
```yaml
Race:
  - update-all:
      $where: def.RaceId >= 0 and def.RaceId < 8
      Bonuses:
        - Type: CounterEspionage
          Amount: value + 0.1
```

From debug log it seems it is executed 3 times and as result ex. Zenox race selection page show 40% Counter Espionage bonus (expected is 20%, from 10% original bonus).

Is it a bug or some problem in patch file?
From Debug console log it seems it is updating 2x at game start and then another 1x time when selecting start new game button.

BTW. Thanks for great work!

**Comment by Tyler-IN** [comment]
Race definitions are patched once on start up; the game replaces them and they are patched again during galaxy generation, so should be twice. So thankfully, that also means if you see it 3 times then it should be effective twice, not 3 times.

Let's see your `debug.log`. You should join the discord to speed up fixing this - easier to get a tight dev-test cycle going.

**Comment by grad-michal** [comment]
Hi, 

Log file attached below.
[debug.log](https://github.com/DW2MC/DW2ModLoader/files/8458338/debug.log)

There must be something more to it as you can see for human it changed from base 0% to 35%...
![human - counter espionage - no patch](https://user-images.githubusercontent.com/3304135/162602935-bd1bdbbf-554a-4531-bbbf-8daa1d3ff61c.PNG)
![human - counter espionage](https://user-images.githubusercontent.com/3304135/162602831-3b1f5a79-0b5a-4a92-9bf2-936938b4df05.PNG)

I believe that for human if Type: CounterEspionage does not match it just update first value (research in that case).
It propably should skip that race (and I should separate changing value for races that already contains CounterEspionage) and those that do not have any bonus) or assume value is 0 and add new element to list.

**Comment by TYoung86** [comment]
this replaces the first bonus with a CounterEspionage bonus...
```yml
Race:
  - update-all:
      $where: def.RaceId >= 0 and def.RaceId < 8
      Bonuses:
        - Type: CounterEspionage
          Amount: value + 0.1
```
I think you want to change specific bonuses...

this finds a CounterEspionage bonus and updates it...
not sure if this will work in 1.2.1 but maybe.
```yml
Race:
  - update-all:
      $where: def.RaceId >= 0 and def.RaceId < 8
      Bonuses:
        (txt(item.Type) is "CounterEspionage"):
          Amount: value + 0.1
```
however, there is no case for "add if not found" yet.


you can just try adding a flat bonus to all;
```yml
Race:
  - update-all:
      $where: def.RaceId >= 0 and def.RaceId < 8
      Bonuses:
        $add:
          - Type: CounterEspionage
            Amount: 0.1
```
